### ISSUE TITLE
[Refactor/State] Switcher

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/element#181]
- [x] needs switch in state
- [x] remove/add elements
- [x] map properties and property method
- [x] be able to map the property method to a subscription (needs to get synced)
- [ ] animation

**Comment by youzi** [comment]
```js
// some switcher code
var switcher = {
  $: 'navigation',
  $map (state) {
    if (state.parent.key === 'episodes') {
      return 'episode'
    }
    if (state.parent.key === 'channels') {
      return 'channel'
    }
    if (state.parent.key === 'shows') {
      return 'show'
    }
  },
  properties: {
    discover: {
      type: 'page-discover'
    },
    episode: {
      type: 'page-episode'
    },
    channels: {
      type: 'page-channels'
    },
    channel: {
      type: 'page-channel'
    },
    shows: {
      type: 'page-shows'
    },
    show: {
      type: 'page-show'
    }
  }
}

**Comment by youzi** [comment]
While mapping: How do I know if something is an element?

**Comment by jimdebeer** [comment]
- needs perfect remove handle (can already start) in state (no nested! except /w flag)

**Comment by jimdebeer** [comment]
pay special attention to order stuff just like collection you may need to do this in `dom/create/apppend.findnode`
```javascript
function findNode (uid, tree, target, nextChild) {
  const len = target._$length
  if (len) {
    for (let i = len; i > 0; i--) {
      tree = tree._p
    }
  } else if (target.$ && target.$ !== true) {
    tree = tree._p
  }
  if (nextChild._$length) {
    let resultTree
    if (nextChild.isCollection || nextChild.isSwitcher) { // never tested so try!
       resultTree = get(tree, nextChild.$.slice(0, -1))
    } else {
       resultTree = get(tree, nextChild.$)
    }
    return resultTree && resultTree._[uid]
  } else if (nextChild.$ && nextChild.$ !== true) {
    return tree[nextChild.$] && tree[nextChild.$]._[uid]
  } else {
    return tree._[uid]
  }
}

**Comment by youzi** [comment]
**TODO**
- in rendermultiple
  - when type === switch
  --> modify the tList, concat the list of this key (ie show)

**Comment by youzi** [comment]
**TODO**
Chek if it's correct to have $switch children have the parent pointing to $switch.parent
