### ISSUE TITLE
[Animation] Finish animation checklist

### ISSUE THREAD

**Issue by youzi** [vigour-io/element#50]
- [ ] Handle adding/removing listeners on frame Observable (pause/play)
- [ ] Handle double updates when using multiple transform values (eg $x and $y)
- [ ] Block animation on drag(gable)
- [ ] Start property
- [ ] Make testcases (many!)
